# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '../..'

def build(bld):
    bld.objects(
        target='get-objects',
        source=bld.path.ant_glob('*.cpp', excl='main.cpp'),
        use='core-objects')

    bld.program(
        target=f'{top}/bin/ndnget',
        name='ndnget',
        source='main.cpp',
        use='get-objects')

    # backward compatibility
    bld.symlink_as('${BINDIR}/ndncatchunks', 'ndnget')
