# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '..'

def build(bld):
    if not bld.env['WITH_TESTS']:
        return

    tools = bld.path.ant_glob('*', dir=True, src=False)

    bld(target='../unit-tests',
        features='cxx cxxprogram',
        source=bld.path.ant_glob('**/*.cpp'),
        use=['core-objects'] + ['%s-objects' % tool for tool in tools],
        headers='../common.hpp boost-test.hpp',
        )
