# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '..'

def build(bld):
    bld.program(
        target='../unit-tests',
        name='unit-tests',
        source=bld.path.ant_glob(['*.cpp'] + ['%s/**/*.cpp' % tool for tool in bld.env.BUILD_TOOLS]),
        use=['core-objects'] + ['%s-objects' % tool for tool in bld.env.BUILD_TOOLS],
        install_path=None)
