# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '../..'

def build(bld):
    bld.objects(
        target='chunks-objects',
        source=bld.path.ant_glob('putchunks/*.cpp', excl='putchunks/main.cpp'),
        use='core-objects')

    bld.program(
        target=f'{top}/bin/ndnputchunks',
        name='ndnputchunks',
        source='putchunks/main.cpp',
        use='chunks-objects')
