# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '../..'

def build(bld):
    bld(features='cxx',
        name='dissect-objects',
        source=bld.path.ant_glob('*.cpp', excl='main.cpp'),
        includes='.',
        export_includes='.',
        use='core-objects')

    bld(features='cxx cxxprogram',
        target='../../bin/ndn-dissect',
        source='main.cpp',
        use='dissect-objects')
