# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '../..'

def build(bld):
    bld.program(
        features='cxx',
        target='../../bin/ndn-dissect',
        source='ndn-dissect.cpp',
        use='core-objects',
        )
