# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '../..'

def build(bld):
    bld.objects(
        target='dissect-objects',
        source=bld.path.ant_glob('*.cpp', excl='main.cpp'),
        use='core-objects')

    bld.program(
        target='../../bin/ndn-dissect',
        name='ndn-dissect',
        source='main.cpp',
        use='dissect-objects')
