# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-
top = '../..'

def build(bld):
    bld(features=['cxx'],
        name="pib-objects",
        target="pib-objects",
        source=bld.path.ant_glob('**/*.cpp', excl=['ndn-pib.cpp']),
        use='core-objects',
        install_path=None)

    bld(features=['cxx', 'cxxprogram'],
        target='../../bin/ndn-pib',
        source='ndn-pib.cpp',
        use='pib-objects')
